### ISSUE TITLE
.ENV parameter not pre-populated

### ISSUE THREAD

**Issue by paulioceano** [auth0-community/auth0-symfony-api-samples#15]
After downloading the sample, the parameter ´AUTH0_AUDIENCE´ is not prepopulated in the .env file.

![screenshot_4](https://user-images.githubusercontent.com/15818783/44474693-45248700-a601-11e8-903f-bd1aa07f62ae.png)

**Comment by jerdog** [comment]
Can you provide the link you downloaded this from? I am not even seeing a .env file included in the quickstart / sample download.

**Comment by albertoperdomo** [comment]
Hello @paulioceano,

we had some issues with the logic that injects the env vars, which were fixed yesterday.
Can you please test again and update this issue according to the result (update with a comment, close if appropriate) ?

Thanks!

**Comment by paulioceano** [comment]
Hello @albertoperdomo.

In this case, Audience parameter is still not filled in the .env file when sample is downloaded from the QS tutorial (https://auth0.com/docs/quickstart/backend/symfony)
